export default Object.freeze({
  Home: 'Home',
  MovieList: 'MovieList',
  RegisterScreen: 'RegisterScreen',
  LoginScreen: 'LoginScreen',
  GetStarted: 'GetStarted',
  AboutMe: 'AboutMe',
  // Credit: 'Credit',
  // Order: 'Order',
  // Account: 'Account',
  AppTabNavigation: 'AppTabNavigation',
  AppWebViewScreen: 'AppWebViewScreen',
  // RepaymentPlanScreen: 'RepaymentPlanScreen',
  // PinScreen: 'PinScreen',
  // FaceIdScreen: 'FaceIdScreen',
});
