export default Object.freeze({
  SIGN_UP_SCREEN: 'SignUpScreen',
  SIGN_IN_SCREEN: 'SignInScreen',
  ONBOARDING_SCREEN: 'OnboardingScreen',
  OTPScreen: 'OTPScreen',
  SignUpSuccessfulScreen: 'SignUpSuccessfulScreen',
  DashboardScreen: 'DashboardScreen',
  CategoryScreen: 'CategoryScreen',
  ListScreen: 'ListScreen',
  SettingsScreen: 'SettingsScreen',
  TabNavigation: 'TabNavigation',
  DrawalNavigation: 'DrawalNavigation',
  SignUpPasswordScreen: 'SignUpPasswordScreen',
  PasswordResetScreen: 'PasswordResetScreen',
  ForgetPasswordScreen: 'ForgetPasswordScreen',
  ForgetPasswordCheckEmailScreen: 'ForgetPasswordCheckEmailScreen',
  PasswordResetSuccessfulScreen: 'PasswordResetSuccessfulScreen',
  ForgetPasswordOTPScreen: 'ForgetPasswordOTPScreen',
  ProductDetailsScreen: 'ProductDetailsScreen',
  MainAppNavigation: 'MainAppNavigation',
  AddReviewScreen: 'AddReviewScreen',
  ListDetailsScreen: 'ListDetailsScreen',
  DeliveryDetailsScreen: 'DeliveryDetailsScreen',
  ListSummaryScreen: 'ListSummaryScreen',
  NotificationScreen: 'NotificationScreen',
  EditProfileScreen: 'EditProfileScreen',
  FeedbacksScreen: 'FeedbacksScreen',
  OrderHistoryScreen: 'OrderHistoryScreen',
  ReferralsScreen: 'ReferralsScreen',
  SubscriptionScreen: 'SubscriptionScreen',
  WalletScreen: 'WalletScreen',
  OrderHistoryDetailsScreen: 'OrderHistoryDetailsScreen',
  Complement: 'Complement',
  Productrequest: 'Product request',
  ComplaintScreen: 'ComplaintScreen',
  ProductRequestScreen: 'ProductRequestScreen',
  MyWebView: 'MyWebView',
});
