export default Object.freeze({
  SIGN_UP_SCREEN: 'SignUpScreen',
  SIGN_IN_SCREEN: 'SignInScreen',
  ONBOARDING_SCREEN: 'OnboardingScreen',
  OTPScreen: 'OTPScreen',
  SignUpSuccessfulScreen: 'SignUpSuccessfulScreen',
  DashboardScreen: 'DashboardScreen',
  SearchScreen: 'SearchScreen',
  CategoryScreen: 'CategoryScreen',
  ProfileScreen: 'ProfileScreen',
  TabNavigation: 'TabNavigation',
  DrawalNavigation: 'DrawalNavigation',
  SignUpPasswordScreen: 'SignUpPasswordScreen',
  PasswordResetScreen: 'PasswordResetScreen',
  ForgetPasswordScreen: 'ForgetPasswordScreen',
  ForgetPasswordCheckEmailScreen: 'ForgetPasswordCheckEmailScreen',
  PasswordResetSuccessfulScreen: 'PasswordResetSuccessfulScreen',
  ForgetPasswordOTPScreen: 'ForgetPasswordOTPScreen',
  ProductDetailsScreen: 'ProductDetailsScreen',
  MainAppNavigation: 'MainAppNavigation',
  AddReviewScreen: 'AddReviewScreen',
});
