export default Object.freeze({
  overallRating: 'Your overall rating of this product',
  likeOrDislike: 'What did you like or dislike?',
  addReview: 'Add a review',
  categoryTitle: 'Category',
  List: 'List',
  deliveryDetails: 'Delivery Details',
  listSummary: 'Summary',
  settings: 'Settings',
  Notifications: 'Notifications',
  Wallet: 'Wallet',
  Subscription: 'Subscription',
  Referrals: 'Referrals',
  Feedback: 'Feedback',
  OrderHistory: 'Order History',
  Logout: 'Log out',
  Complement: 'Complement',
  Complaint: 'Complaint',
  Productrequest: 'Product request',
  addFeedback: 'Add feedback',
  Description: 'Description',
});
